### ISSUE TITLE
updates

### ISSUE THREAD

**Issue by scratcher28** [mishazawa/nums#1]
Are you planning any updates?

**Comment by mishazawa** [comment]
Hi. I think no, because it's just wrapper around nsfwjs library (link https://github.com/infinitered/nsfwjs). =)

**Comment by scratcher28** [comment]
@mishazawa, yeah, I know that ))
I see you have a different model set (85.4mb) comparing to nsfwjs (21.5mb).
Do you use more accurate one?

**Comment by mishazawa** [comment]
As far as I remember, I took one from this models (https://github.com/gantman/nsfw_model) and preprocess it for nsfwjs (only file container h5 -> json).  Maybe this operation increased file size, idk
